# Generated by Django 4.2.4 on 2023-08-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Attendance'},
        ),
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
