# Generated by Django 4.2.4 on 2023-08-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_time_alter_employee_options_employee_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
