# Generated by Django 4.2.4 on 2023-08-28 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_time_created_time_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(blank=True, choices=[('intern', 'intern'), ('developer', 'developer')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
