# Generated by Django 3.2.12 on 2023-08-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zkteco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
