# Generated by Django 3.2.12 on 2023-08-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zkteco', '0002_user_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
