# Generated by Django 3.2.12 on 2023-08-29 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zkteco', '0003_alter_user_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
