# Generated by Django 3.2.12 on 2023-08-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zkteco', '0004_alter_user_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_in',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='time_out',
            field=models.TimeField(null=True),
        ),
    ]
