# Generated by Django 3.2.12 on 2023-08-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zkteco', '0005_auto_20230829_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('uername', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
                ('time_in', models.TimeField(null=True)),
                ('time_out', models.TimeField(null=True)),
            ],
        ),
    ]
