# Generated by Django 3.2.12 on 2023-08-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zkteco', '0006_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
