# Generated by Django 3.2.12 on 2023-08-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zkteco', '0007_auto_20230829_0945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
