# Generated by Django 3.2.12 on 2023-08-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zkteco', '0009_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='uid',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
