# Generated by Django 3.2.12 on 2023-08-30 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zkteco', '0010_auto_20230830_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
