# Generated by Django 3.2.12 on 2023-08-30 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zkteco', '0012_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emp',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
