# Generated by Django 3.2.12 on 2023-08-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zkteco', '0013_auto_20230830_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('attendance_status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
            ],
        ),
    ]
