# Generated by Django 3.2.12 on 2023-08-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zkteco', '0014_attendancemodel_usermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='position',
        ),
    ]
